version: '2.0'
services:
  trimesh:
    build:
      context: ./docker
      dockerfile: trimesh.Dockerfile
      args:
        UID: $UID
        GID: $GID
    working_dir: /home/user
    volumes:
      - /home/user/:$PWD