version: '2.0'
services:
  trimesh:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        UID: $UID
        GID: $GID
    working_dir: /home/user
    volumes:
      - "$PWD:/home/user/csg"